title:            NSBlog
description:      blogWithAuther:@"邵公奭"
url:              http://john-shaw.github.io
signoff:          邵公奭
disqus_shortname: Shao_JianYong
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: 
  config: false
  id: UA-55487527-2

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          /
    external:     true
  - name:         Email
    url:          mailto:bard2093@gmail.com
    external:     true
  - name:         GitHub
    url:          http://github.com/john-shaw
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
